[build]
  publish = "dist"
  command = "gridsome build"

[build.environment]
  WORDPRESS_URL = "https://demo.wp-api.org"
  
[template.environment]
  WORDPRESS_URL = "Replace me with your Wordpress URL"
